# Swag Little
swagLittle 5 xxx..xxx

# swag dark 1
swag 0 xx....xx
dark 0

# little 1
little 5 xxxxxxxx

# swag 1
swag 0 xxxxxxxx
buttons 1 ........T

# swag 2
swag 1 xxxxxxxx
buttons 0 ........T

# swag 2
swag 2 xxxxxxxx
buttons 1 ........T

# swag 2
swag 3 xxxxxxxx
buttons 1 ........T

# swag 2
swag 4 xxxxxxxx
buttons 1 ........T

# swag 2
swag 5 xxxxxxxx
buttons 1 ........T

# swag 2
swag 6 xxxxxxxx
buttons 1 ........T

# swag 2
swag 7 xxxxxxxx
buttons 1 ........T




