- hosts: all
  gather_facts: yes
  become: yes

  vars:
    zoomachine:
      git_url: https://github.com/yoann-dufresne/ZooMachine-3.git
      path: "{{ansible_env.HOME}}/ZooMachine-3"
      requirement_path: code/slave/raspi/requirements.txt
    update_cache: yes

  tasks:
    - name: install python-apt
      command: apt-get -y install python-apt

    - name: install ubuntu packages
      apt: pkg={{ item }} state=installed update_cache={{ update_cache }}
      with_items:
        - git
        - vim
        - python3
        - python3-pip
        - libsmpeg-dev

    - name: Copy Zoomachine repository
      git: repo="{{zoomachine.git_url}}" dest="{{zoomachine.path}}"

    - name: Install pip dependancies
      pip:
        requirements={{ zoomachine.path }}/{{ zoomachine.requirement_path }} execuable="/usr/bin/pip3"
