- hosts: all
  gather_facts: yes
  become: yes

  vars:
    zoomachine:
      git_url: https://github.com/yoann-dufresne/ZooMachine-3.git
      path: /home/pi/ZooMachine-3
      requirement_path: code/slave/raspi/requirements.txt
    update_cache: yes

  tasks:
    - name: install python-apt
      command: apt-get -y install python-apt

    - name: install ubuntu packages
      apt: pkg={{ item }} state=installed update_cache={{ update_cache }}
      with_items:
        - git
        - vim
        - python3
        - htop
        - python3-pip
        - libsmpeg-dev

    - name: Copy Zoomachine repository
      git: repo="{{zoomachine.git_url}}" dest="{{zoomachine.path}}" force=true
      become_user: pi

    - name: Install pip dependancies
      pip:
        requirements={{ zoomachine.path }}/{{ zoomachine.requirement_path }} executable="/usr/bin/pip3"

    - name: Copy slave systemd init script
      copy: src=init_zoomachine3_slave.service dest=/lib/systemd/system/init_zoomachine3.service owner=root group=root
      when: inventory_hostname != "master.local"

    - name: Copy master systemd init script
      copy: src=init_zoomachine3_master.service dest=/lib/systemd/system/init_zoomachine3.service owner=root group=root
      when: inventory_hostname == "master.local"

    - name: Settup systemd script
      systemd: state=started name=init_zoomachine3.service enabled=True