- hosts: all
  gather_facts: yes
  become: yes

  vars:
    zoomachine:
      git_url: https://github.com/yoann-dufresne/ZooMachine-3.git
      path: /home/pi/ZooMachine-3
      requirement_path: code/slave/raspi/requirements.txt
    update_cache: yes

  tasks:
    - name: install python-apt
      command: apt-get -y install python-apt

    - name: install ubuntu packages
      apt: pkg={{ item }} state=installed update_cache={{ update_cache }}
      with_items:
        - git
        - vim
        - python3
        - htop
        - python3-pip
        - python-dev
        - python3-dev
        - libzmq-dev
        # - libavbin-dev
        # - libavbin0

    - name: Clone Zoomachine repository
      git: repo="{{zoomachine.git_url}}" dest="{{zoomachine.path}}" force=true
      become_user: pi

    - name: Install pip dependancies
      pip:
        requirements={{ zoomachine.path }}/{{ zoomachine.requirement_path }} executable="/usr/bin/pip3"

    - name: Copy slave systemd init script
      copy: src=init_zoomachine3_slave.service dest=/lib/systemd/system/init_zoomachine3.service owner=root group=root force=yes
      when: inventory_hostname != "master"

    - name: Copy master systemd init script
      copy: src=init_zoomachine3_master.service dest=/lib/systemd/system/init_zoomachine3.service owner=root group=root force=yes
      when: inventory_hostname == "master"

    - name: Settup systemd script
      systemd: state=started name=init_zoomachine3.service enabled=True

    - name: Restart services
      systemd: state=restarted name=init_zoomachine3.service enabled=True

    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      become: true
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=60
      become: false